// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzwzglmzjfqekgoretsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6d3pnbG16amZxZWtnb3JldHNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzEwOTgsImV4cCI6MjA2OTQ0NzA5OH0.4vI5Y2af3lAl43bHDI57BO_E3lXe0GRx7uciTu0JvHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});