// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpxwwcruleynfotilhsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFweHd3Y3J1bGV5bmZvdGlsaHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzgwMzcsImV4cCI6MjA2OTQ1NDAzN30.XyTqYSE-_JeCZStEk2LP_R-Ujn58sq1CHDQy6ubMw4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});